/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fuzzy;

import Variables.Value;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sirp2.Observacional;

/**
 *
 * @author mew
 */
public class GUIFuzzy extends javax.swing.JFrame {

    /**
     * Creates new form GUIFuzzy
     */
    LinkedList m;
     LinkedList captura;
     int tipo;
     double a,b,c,d;
    public GUIFuzzy(LinkedList matriz,LinkedList ha,int tipo) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.tipo=tipo;
        m=matriz;
        captura=ha;
        if(tipo==1){
        this.jLabel1.setIcon(new ImageIcon(getClass().getResource("tri.png")));
        this.A.setEditable(true);
        this.B.setEditable(true);
        this.C.setEditable(true);
        this.setTitle("Triangular");
        
        }
        if(tipo==2){
        this.jLabel1.setIcon(new ImageIcon(getClass().getResource("tra.png")));
        this.A.setEditable(true);
        this.B.setEditable(true);
        this.C.setEditable(true);
        this.D.setEditable(true);
        this.setTitle("Trapezoidal");
        
        }
        if(tipo==3){
        this.jLabel1.setIcon(new ImageIcon(getClass().getResource("bell.png")));
        this.A.setEditable(true);
        this.B.setEditable(true);
        this.C.setEditable(true);
        this.setTitle("Bell");
        
        }
        if(tipo==4){
        this.jLabel1.setIcon(new ImageIcon(getClass().getResource("gauss.png")));
        this.A.setEditable(true);
        this.C.setEditable(true);
        this.setTitle("Gauss");
        
        }
        if(tipo==5){
        this.jLabel1.setIcon(new ImageIcon(getClass().getResource("sig.png")));
        this.A.setEditable(true);
        this.B.setEditable(true);
        this.C.setEditable(true);
        this.setTitle("Sigmoidal");
        
        }

    }
    

    private GUIFuzzy() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        C = new javax.swing.JTextField();
        B = new javax.swing.JTextField();
        A = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        D = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("A:");

        jLabel3.setText("B:");

        jLabel4.setText("C:");

        C.setEditable(false);
        C.setText("0");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        B.setEditable(false);
        B.setText("0");

        A.setEditable(false);
        A.setText("0");

        jLabel5.setText("Introduzca valores:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calculator.png"))); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        D.setEditable(false);
        D.setText("0");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        jLabel6.setText("D:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String nam=JOptionPane.showInputDialog("¿Que variable usara?(Val 1)");
            int pos=0;
            for(int x=1;x<this.captura.size();x++)
                if(nam.equals(this.captura.get(x))){
                    pos=x;
                    break;
                }
            if(pos>0){
            this.a=Double.parseDouble(A.getText());
            this.b=Double.parseDouble(B.getText());
            this.c=Double.parseDouble(C.getText());
            this.d=Double.parseDouble(D.getText());
            DefaultTableModel tio=addvalue(pos);
           new Observacional(tio,this.m.size(),this.captura.size()).setVisible(true);
           this.dispose();
            }
            else {
            JOptionPane.showMessageDialog(null, "Variable no existe", "Mensaje de Informacion", JOptionPane.INFORMATION_MESSAGE);
            }
            } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos !!", "Mensaje de Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
private double triangular(double value){
    double r=0.0;
    if(value<=this.a||value>this.c)
        r=0.0;
    if(this.a<=value&&value<this.b)
        r=(value-this.a)/(this.b-this.a);
    if(this.b<=value&&value<this.c)
         r=(this.c-value)/(this.c-this.b);
    
    return r;
}
private double trapezoidal(double value){
    double r=0.0;
    if(value<=this.a||value>this.d)
        r=0.0;
    if(this.a<=value&&value<this.b)
        r=(value-this.a)/(this.b-this.a);
    if(this.b<=value&&value<this.c)
         r=1;
     if(this.c<=value&&value<this.d)
        r=(this.d-value)/(this.d-this.c);
    
    return r;
}
private double bell(double value){
    double r=1/(1+Math.pow(Math.abs((value-c)/a),2*b));
    return r;
}
private double gauss(double value){
    double r=Math.pow(Math.E,-0.5*Math.pow((value-c)/a,2));
    return r;
}
private double sig(double value){
    double r=0;
     if(value<=this.a)
         r=0;
     if(this.a<=value&&value<this.b)
         r=2*Math.pow((value-this.a)/(this.c-this.a),2);
      if(this.b<=value&&value<this.c)
          r=1-(2*Math.pow((value-this.c)/(this.c-this.a),2));
     if(value>this.c)
         r=1;
    // return 1.0 / (1 + Math.exp(-value));
    return r;
}
    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DActionPerformed
 private DefaultTableModel addvalue(int p) {
      DefaultTableModel  variables = new DefaultTableModel();
        variables.addColumn("Nombre");
        for (int x = 1; x < captura.size(); x++) {
            variables.addColumn(captura.get(x));
        }
        variables.addColumn("*"+JOptionPane.showInputDialog("¿Nombre de la nueva variable?"));
        String[] Dato = new String[captura.size()+1];
        for (int x = 0; x < this.m.size(); x++) {
            Value v = (Value) m.get(x);
            Dato[0] = v.getName();
            for (int y = 0; y < v.getValue().size(); y++) {
                    Dato[y + 1] = (String) v.getValue().get(y);
                }
             if(this.tipo==1)
                        Dato[v.getValue().size()+1] = ""+triangular(Double.parseDouble(Dato[p]));
             if(this.tipo==2)
                        Dato[v.getValue().size()+1] = ""+trapezoidal(Double.parseDouble(Dato[p]));
             if(this.tipo==3)
                        Dato[v.getValue().size()+1] = ""+bell(Double.parseDouble(Dato[p]));
             if(this.tipo==4)
                     Dato[v.getValue().size()+1] = ""+gauss(Double.parseDouble(Dato[p]));
            if(this.tipo==5)
                     Dato[v.getValue().size()+1] = ""+sig(Double.parseDouble(Dato[p]));
            variables.addRow(Dato);
        }
        return variables;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFuzzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFuzzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFuzzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFuzzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFuzzy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField B;
    private javax.swing.JTextField C;
    private javax.swing.JTextField D;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
